### ISSUE TITLE
Torrent Client On Same Host?

### ISSUE THREAD

**Issue by AnthonyTippy** [JamesRy96/audiobookbay-automated#13]
Love the work you've added here.  I created a fork that Im currently working on trying to make a docker-compose file to host qbittorrent and audibookbay-automated on the same host

I've run into an issue where I can't seem to get `DL_HOST=192.168.xxx.xxx` to connect to the download client

I've tried `localhost`, `0.0.0.0` as well as the direct IP

- `localhost` - audiobookbay-automated webserver works and can query audiobook bay, but can't connect to the qbittorrent server
- `0.0.0.0` - audiobookbay-automated webserver works and can query audiobook bay, but can't connect to the qbittorrent server
- `192.168.1.XX` (direct IP declaration) audiobookbay-automated webserver can connect to torrent client but audibookbay search query just spins indefinitely. 
Any thoughts on what might be going wrong?

**Comment by AnthonyTippy** [comment]
update:

not sure if my IP has been blocked or something but ping requests to audiobookbay.is and audiobookbay.lu are unsuccessful :(  

I'll try again in a couple days

**Comment by AnthonyTippy** [comment]
Oh gotcha!  I figured it was something I was missing.  Thanks so much!  I'll take a look

**Comment by AnthonyTippy** [comment]
well I got it working as best I can tell but still running into issues with the connection being accepted


```
audiobookbay-downloader    | requests.exceptions.ConnectionError: HTTPSConnectionPool(host="%20'theaudiobookbay.se'", port=443): Max retries exceeded with url: /page/1/?s=wicked&cat=undefined%2Cundefined (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x78092a6d5f30>: Failed to resolve '%20'theaudiobookbay.se'' ([Errno -2] Name or service not known)"))
```

**Comment by AnthonyTippy** [comment]
gotcha yeah I figured as much.  Thanks for all the help and great work.  I've been looking for something like this for a minute and was pleasantly surprised to find it!

**Comment by moonblade** [comment]
They have a rate limiter on audiobookbay side that seems to activate (sporadically) not just on client ip and too much calls, but whether the call is made with curl/api (without origin headers as far as I can tell). So even something as small as three calls was blocking me for a while.

**Comment by crispybegs** [comment]
> The comment messed the formatting up, [here's a link](https://code.jamesry96.dev/s/d5548f231b54a9a28cc2bfb8f79e972b) to check the example out.

what on earth?

<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/72535b85-d372-4451-881c-0d98de4c08e4" />

**Comment by crispybegs** [comment]
> Give it another shot. My users are mostly US centric so I had an overly generic firewall rule in place.

thanks. very weird. my previous installation (which has never worked tbh) now loads up the search page but when clicking to start search returns this

<img width="497" alt="Image" src="https://github.com/user-attachments/assets/e4c155ef-1ad0-439f-86fa-92b1d4edf9d0" />

I took your compose above, in case there was an issue with my old one, and installed it on a completely different server, and got exactly the same thing.

<img width="497" alt="Image" src="https://github.com/user-attachments/assets/e4c155ef-1ad0-439f-86fa-92b1d4edf9d0" />

**Comment by AnthonyTippy** [comment]
I haven't gotten a chance to try it recently but `audiobookbay.is` seems to be down or unreachable at least by me

I was trying to get `http://theaudiobookbay.se/` to work but your docker images doesn't like the http

**Comment by AnthonyTippy** [comment]
same issue as you had I'm afraid 

![Image](https://github.com/user-attachments/assets/cc15cec0-aedc-4b9a-8c83-a15b56578e5d)

**Comment by crispybegs** [comment]
> Looks like the container is not able to connect to audiobookbay.is, are you able to open the site in a browser on the same network?
> 
> Maybe another mirror would work.

yes i can view it in a browser without an issue, and the same thing happens with `theaudiobookbay.se` also.

I suspect this may be something to do with my ISP (virgin media / uk). I had a similar issue with Calibre-Web-Automated-Downloader, where some of us were able to view the site in-browser but the download process failed. I ended up putting that in the same stack with Gluetun & qbit, which solved it. You can read that resolution [here](https://github.com/calibrain/calibre-web-automated-book-downloader/issues/59) - it may possibly help?

I'm not 10% sure though, as I've tried putting audiobookbay-automated in the same stack with those others but still getting the same result. My compose is:

```
services:
  gluetun:
    #image: qmcgaw/gluetun:v3.35.0
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /home/crispy/docker/gluetun2/config:/config
    ports:
     # - "8082:8080" # qbittorrent WebUI
      - "8009:8000/tcp"
      - "6081:6881"
      - "6081:6881/udp"
      - "6011:6011"
      - "6012:6012"
      - "8084:8084" #CAWD port
      - "5078:5078" #audiobookbay downloader port
      
    environment:
      VPN_SERVICE_PROVIDER: windscribe
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: [redacted]
      WIREGUARD_ADDRESSES: 100.xxx.xx.xxx/32
      WIREGUARD_PRESHARED_KEY: [redacted]
      SERVER_REGIONS: Spain
      SERVER_CITIES: Madrid
      PUBLICIP_API: ipinfo
      PUBLICIP_API_TOKEN: [redacted]

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_vpn
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=6011
    volumes:
      - /home/crispy/docker/qbittorrent/config:/config
      - /home/crispy/drives/drive1/data/torrents:/data/torrents
    depends_on:
      gluetun:
        condition: service_healthy

  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    network_mode: "service:gluetun"
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      USE_CF_BYPASS: false
    #ports:
     # - 8084:8084 this was put up in the gluetun compose ^
    restart: unless-stopped
    volumes:
      - /home/crispy/drives/drive1/data/media/books:${INGEST_DIR:-/cwa-book-ingest}
    depends_on:
      gluetun:
        condition: service_healthy      

  audiobookbay-downloader:
    image: ghcr.io/jamesry96/audiobookbay-automated:latest
    network_mode: "service:gluetun"
    #ports:
     # - "5078:5078" #this was put up in the gluetun compose ^
    container_name: audiobookbay-downloader
    environment:
      - DOWNLOAD_CLIENT=qbittorrent
      - DL_HOST=192.168.1.63
      - DL_PORT=6011
      - DL_USERNAME=crispy
      - DL_PASSWORD=[redacted]
      - DL_CATEGORY=audiobooks
      - ABB_HOSTNAME='audiobookbay.se'
      #- PUID=1000
      #- PGID=1000
      - SAVE_PATH_BASE=/home/crispy/drives/drive1/data/media/audiobooks/
     # - NAV_LINK_NAME=Open Audiobook Player #Optional
     # - NAV_LINK_URL=https://audiobooks.yourdomain.com/ #Optional
    depends_on:
      gluetun:
        condition: service_healthy      
```
