### ISSUE TITLE
Deploy error in portainer

### ISSUE THREAD

**Issue by crispybegs** [JamesRy96/audiobookbay-automated#3]
niche case, i grant you, but my ISP (virgin media uk) has blocked vanilla access to ABB so a vpn is required.
i already have qbittorrent and calibre web automated downloader (a service almost identical to yours) in the same portainer compose as gluetun, so that both services can run through a vpn.

i'm trying to get this up and running in the same gluetun compose but I'm running into this error when deploying:

```
Failure
Failed to deploy a stack: validating /data/compose/12/docker-compose.yml: services.audiobookbay-downloader.ports must be a list
```

I've never seen that message before and I'm not sure how to go about fixing it.
This is my full compose. Any ideas?

```
services:
  gluetun:
    #image: qmcgaw/gluetun:v3.35.0
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /home/crispy/docker/gluetun2/config:/config
    ports:
     # - "8082:8080" # qbittorrent WebUI
      - "8009:8000/tcp"
      - "6081:6881"
      - "6081:6881/udp"
      - "6011:6011"
      - "8084:8084" #CAWD port
      - "5078:5078" #audiobookbay downloader port
      
    environment:
      VPN_SERVICE_PROVIDER: windscribe
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: xxxxxx
      WIREGUARD_ADDRESSES: xxxxxx/32
      WIREGUARD_PRESHARED_KEY: xxxxxx
      SERVER_REGIONS: Spain
      SERVER_CITIES: Madrid
      PUBLICIP_API: ipinfo
      PUBLICIP_API_TOKEN: xxxxx

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_vpn
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=6011
    volumes:
      - /home/crispy/docker/qbittorrent/config:/config
      - /home/crispy/drives/drive1/data/torrents:/data/torrents
    depends_on:
      gluetun:
        condition: service_healthy

  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    network_mode: "service:gluetun"
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      USE_CF_BYPASS: false
    #ports:
     # - 8084:8084 this was put up in the gluetun compose ^
    restart: unless-stopped
    volumes:
      - /home/crispy/drives/drive1/data/media/books:${INGEST_DIR:-/cwa-book-ingest}
    depends_on:
      gluetun:
        condition: service_healthy      

  audiobookbay-downloader:
    image: ghcr.io/jamesry96/audiobookbay-automated:latest
    network_mode: "service:gluetun"
    ports:
    #  - "5078:5078" #this was put up in the gluetun compose ^
    container_name: audiobookbay-downloader
    environment:
      - DOWNLOAD_CLIENT=qbittorrent
      - DL_HOST=192.168.1.63
      - DL_PORT=6011
      - DL_USERNAME=xxxxx
      - DL_PASSWORD=xxxx
      - DL_CATEGORY=audiobooks
      - PUID=1000
      - PGID=1000
     # - SAVE_PATH_BASE=/audiobooks
     # - NAV_LINK_NAME=Open Audiobook Player #Optional
     # - NAV_LINK_URL=https://audiobooks.yourdomain.com/ #Optional
    depends_on:
      gluetun:
        condition: service_healthy      
```

**Comment by crispybegs** [comment]
ok, i fiddled some more and got it _kind of_ working. leaving the compose here in case anyone wants a gluetun / qbittorrent / calibre web automated downloader / audiobookbay automate compose to play with:

```
services:
  gluetun:
    #image: qmcgaw/gluetun:v3.35.0
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /directory/of/your/choice/config:/config
    ports:
      - "8009:8000/tcp"
      - "6081:6881"
      - "6081:6881/udp"
      - "6011:6011" # qbittorrent WebUI
      - "6012:6012"
      - "8084:8084" #CAWD WebUI
      - "5078:5078" #audiobookbay downloader WebUI
      
    environment:
      VPN_SERVICE_PROVIDER: name_of_your_vpn_provider
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: put_your_private_key_here
      WIREGUARD_ADDRESSES: and_the_IP_address_here
      WIREGUARD_PRESHARED_KEY: put_your_preshared_key_here
      SERVER_REGIONS: your-preferred-country
      SERVER_CITIES: your-preferred-city
      PUBLICIP_API: ipinfo
      PUBLICIP_API_TOKEN: your_public_IP_token

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_vpn
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=6011
    volumes:
      - /directory/of/your/choice/config:/config
      - /directory/of/your/choice/torrents:/data/torrents
    depends_on:
      gluetun:
        condition: service_healthy

  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    network_mode: "service:gluetun"
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      CLOUDFLARE_PROXY_URL: http://cloudflarebypassforscraping:8000
      INGEST_DIR: /cwa-book-ingest
      BOOK_LANGUAGE: en
      USE_CF_BYPASS: false
    #ports:
     # - 8084:8084 this was put up in the gluetun compose ^
    restart: unless-stopped
    volumes:
      - /directory/of/your/choice/books:${INGEST_DIR:-/cwa-book-ingest}
    depends_on:
      gluetun:
        condition: service_healthy      

  audiobookbay-downloader:
    image: ghcr.io/jamesry96/audiobookbay-automated:latest
    network_mode: "service:gluetun"
    #ports:
     # - "5078:5078" #this was put up in the gluetun compose ^
    container_name: audiobookbay-downloader
    environment:
      - DOWNLOAD_CLIENT=qbittorrent
      - DL_HOST=192.168.1.63
      - DL_PORT=6012
      - DL_USERNAME=your_username
      - DL_PASSWORD=your_password
      - DL_CATEGORY=audiobooks
      - PUID=1000
      - PGID=1000
     # - SAVE_PATH_BASE=/audiobooks
     # - NAV_LINK_NAME=Open Audiobook Player #Optional
     # - NAV_LINK_URL=https://audiobooks.yourdomain.com/ #Optional
    depends_on:
      gluetun:
        condition: service_healthy    
```    

So after fixing this up, the ABBA UI loaded and i was able to successfully search for, in this case, 'charles dickens'. Results were returned and i clicked one to download. This seemed to work and switching over to the qbit tab I can see action, of a sort:

<img width="931" alt="Image" src="https://github.com/user-attachments/assets/bc6c7a19-ab70-4b5d-85e8-0a4b4a018162" />

I don't know why it's not downloading, but I was more concerned with actually proving the concept first.

While it was trying to download I went back to the ABBA ui and tried to switch to the 'Status' tab, however this result in the whole UI hanging. Refreshing the page eventually got me back to being able to search, so I searched for a very popular author, got results, and clicked to download several audiobooks, however the page totally hung and eventually gave me this message:

<img width="453" alt="Image" src="https://github.com/user-attachments/assets/9eb89e20-6a4a-477d-9b9c-87cb8c7e3688" />

Relaoding the page is giving me search results again, but clicking to download does nothing at all, and clicking on the status tab just makes the page hang... so not sure why any of that is happening.

The container doesn't seem to be very active, just showing this:

```
192.168.1.30 - - [19/Jan/2025 22:50:37] "GET / HTTP/1.1" 200 -

192.168.1.30 - - [19/Jan/2025 22:50:38] "GET /static/css/search.css HTTP/1.1" 304 -

192.168.1.30 - - [19/Jan/2025 22:50:38] "GET /static/css/style.css HTTP/1.1" 304 -

192.168.1.30 - - [19/Jan/2025 22:52:42] "POST / HTTP/1.1" 200 -

192.168.1.30 - - [19/Jan/2025 22:52:42] "GET /static/css/style.css HTTP/1.1" 304 -

192.168.1.30 - - [19/Jan/2025 22:52:42] "GET /static/css/search.css HTTP/1.1" 304 -

192.168.1.30 - - [19/Jan/2025 22:53:18] "POST / HTTP/1.1" 200 -

192.168.1.30 - - [19/Jan/2025 22:53:18] "GET /static/css/style.css HTTP/1.1" 304 -

192.168.1.30 - - [19/Jan/2025 22:53:18] "GET /images/default_cover.jpg HTTP/1.1" 404 -

192.168.1.30 - - [19/Jan/2025 22:53:18] "GET /static/css/search.css HTTP/1.1" 304 -

192.168.1.30 - - [19/Jan/2025 22:53:40] "GET /status HTTP/1.1" 500 -
```
..and no activity at all for the last 3 minutes, while the UI spins trying to open the status tab without success.
Actually, as I'm typing this the UI just crashed and the page now just says this:

`{"message":"Failed to fetch torrent status: Failed to connect to qBittorrent. Unknown Error: ConnectTimeout(MaxRetryError(\"HTTPConnectionPool(host='192.168.1.63', port=6012): Max retries exceeded with url: /api/v2/auth/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7b01a1da9ba0>, 'Connection to 192.168.1.63 timed out. (connect timeout=15.1)'))\"))"}`
